# Site settings
title: "L'Écho des Songes"
description: "Voyages au pays des sons méconnus"
podcast-description: "Audiothèque méditative des mystères de l'espace, des abysses et des phénomènes terrestres insolites."
url: "https://echosdessonges.github.io"
baseurl: ""
author:
  name: "Le Moine Lunaire"
  email: ""
  url: "https://echosdesonges.github.io"
permalink: pretty
keywords: [podcast, sons, meditation, espace, abysses, mystere]

# Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

# Pagination
paginate: 5
paginate_path: "/page-:num/"

# Sass
sass:
  style: compressed
  sourcemap: never

# SEO
twitter:
  username: 
  card: summary
facebook:
  app_id: 
logo: /assets/img/logo-moine.png # On nommera ton image comme ça plus tard
social:
  name: L'Écho des Songes
  links:
    - https://github.com/echosdesonges

lang: fr

# Podcast Metadata (Optionnel mais propre)
podcast_title: "L'Écho des Songes"
podcast_author: "Le Moine Lunaire"
podcast_subtitle: "Voyages au pays des sons méconnus"
podcast_summary: "Une collection de sons étranges et méditatifs captés aux quatre coins de l'univers."
podcast_description: "Audiothèque immersive pour explorateurs sonores."
podcast_explicit: "no"
podcast_type: episodic
podcast_lang: fr
podcast_launch: "2024-05-20"
podcast_copyright: "© L'Écho des Songes"
podcast_artwork: "/assets/img/logo-moine.png"
